from flask import Flask, request, jsonify
import pandas as pd

data = [
  {
    "antecedents": "frozenset({'Avocado Toast'})",
    "consequents": "frozenset({'Coffee'})",
    "antecedent support": 0.05,
    "consequent support": 0.15,
    "support": 0.05,
    "confidence": 1,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": "inf",
    "zhangs_metric": 0.8947368421052632,
    "jaccard": 0.3333333333333333,
    "certainty": 1,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Coffee'})",
    "consequents": "frozenset({'Avocado Toast'})",
    "antecedent support": 0.15,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.33333333333333337,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": 1.425,
    "zhangs_metric": 1,
    "jaccard": 0.3333333333333333,
    "certainty": 0.29824561403508776,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Avocado Toast'})",
    "consequents": "frozenset({'Fruit Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Fruit Bowl'})",
    "consequents": "frozenset({'Avocado Toast'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Masala Dosa'})",
    "consequents": "frozenset({'Biryani'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Biryani'})",
    "consequents": "frozenset({'Masala Dosa'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Biryani'})",
    "consequents": "frozenset({'Paneer Tikka'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Paneer Tikka'})",
    "consequents": "frozenset({'Biryani'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Boiled Eggs'})",
    "consequents": "frozenset({'Omelette'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Omelette'})",
    "consequents": "frozenset({'Boiled Eggs'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Protein Shake'})",
    "consequents": "frozenset({'Boiled Eggs'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Boiled Eggs'})",
    "consequents": "frozenset({'Protein Shake'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Cupcake'})",
    "consequents": "frozenset({'Brownie'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Brownie'})",
    "consequents": "frozenset({'Cupcake'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Ice Cream'})",
    "consequents": "frozenset({'Brownie'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Brownie'})",
    "consequents": "frozenset({'Ice Cream'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fries'})",
    "consequents": "frozenset({'Burger'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Burger'})",
    "consequents": "frozenset({'Fries'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Iced Herbal Tea'})",
    "consequents": "frozenset({'Burger'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Burger'})",
    "consequents": "frozenset({'Iced Herbal Tea'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Greek Yogurt'})",
    "consequents": "frozenset({'Cereal Bowl'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Cereal Bowl'})",
    "consequents": "frozenset({'Greek Yogurt'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Trail Mix'})",
    "consequents": "frozenset({'Cereal Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Cereal Bowl'})",
    "consequents": "frozenset({'Trail Mix'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Cheesecake'})",
    "consequents": "frozenset({'Garlic Bread'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Garlic Bread'})",
    "consequents": "frozenset({'Cheesecake'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Cheesecake'})",
    "consequents": "frozenset({'Pasta'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Pasta'})",
    "consequents": "frozenset({'Cheesecake'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Chia Pudding'})",
    "consequents": "frozenset({'Quinoa Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Quinoa Bowl'})",
    "consequents": "frozenset({'Chia Pudding'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Chia Pudding'})",
    "consequents": "frozenset({'Roasted Veggies'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Roasted Veggies'})",
    "consequents": "frozenset({'Chia Pudding'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fries'})",
    "consequents": "frozenset({'Coconut Water'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Coconut Water'})",
    "consequents": "frozenset({'Fries'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Coconut Water'})",
    "consequents": "frozenset({'Pizza'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Pizza'})",
    "consequents": "frozenset({'Coconut Water'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Donut'})",
    "consequents": "frozenset({'Coffee'})",
    "antecedent support": 0.05,
    "consequent support": 0.15,
    "support": 0.05,
    "confidence": 1,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": "inf",
    "zhangs_metric": 0.8947368421052632,
    "jaccard": 0.3333333333333333,
    "certainty": 1,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Coffee'})",
    "consequents": "frozenset({'Donut'})",
    "antecedent support": 0.15,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.33333333333333337,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": 1.425,
    "zhangs_metric": 1,
    "jaccard": 0.3333333333333333,
    "certainty": 0.29824561403508776,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Coffee'})",
    "consequents": "frozenset({'Fruit Bowl'})",
    "antecedent support": 0.15,
    "consequent support": 0.1,
    "support": 0.1,
    "confidence": 0.6666666666666667,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.085,
    "conviction": 2.7000000000000006,
    "zhangs_metric": 1,
    "jaccard": 0.6666666666666667,
    "certainty": 0.6296296296296298,
    "kulczynski": 0.8333333333333334
  },
  {
    "antecedents": "frozenset({'Fruit Bowl'})",
    "consequents": "frozenset({'Coffee'})",
    "antecedent support": 0.1,
    "consequent support": 0.15,
    "support": 0.1,
    "confidence": 1,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.085,
    "conviction": "inf",
    "zhangs_metric": 0.9444444444444444,
    "jaccard": 0.6666666666666667,
    "certainty": 1,
    "kulczynski": 0.8333333333333334
  },
  {
    "antecedents": "frozenset({'Coffee'})",
    "consequents": "frozenset({'Pancakes'})",
    "antecedent support": 0.15,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.33333333333333337,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": 1.425,
    "zhangs_metric": 1,
    "jaccard": 0.3333333333333333,
    "certainty": 0.29824561403508776,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Pancakes'})",
    "consequents": "frozenset({'Coffee'})",
    "antecedent support": 0.05,
    "consequent support": 0.15,
    "support": 0.05,
    "confidence": 1,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": "inf",
    "zhangs_metric": 0.8947368421052632,
    "jaccard": 0.3333333333333333,
    "certainty": 1,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Coffee'})",
    "consequents": "frozenset({'Waffles'})",
    "antecedent support": 0.15,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.33333333333333337,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": 1.425,
    "zhangs_metric": 1,
    "jaccard": 0.3333333333333333,
    "certainty": 0.29824561403508776,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Waffles'})",
    "consequents": "frozenset({'Coffee'})",
    "antecedent support": 0.05,
    "consequent support": 0.15,
    "support": 0.05,
    "confidence": 1,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": "inf",
    "zhangs_metric": 0.8947368421052632,
    "jaccard": 0.3333333333333333,
    "certainty": 1,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Croissant'})",
    "consequents": "frozenset({'Greek Yogurt'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Greek Yogurt'})",
    "consequents": "frozenset({'Croissant'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Croissant'})",
    "consequents": "frozenset({'Muffin'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Muffin'})",
    "consequents": "frozenset({'Croissant'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Cupcake'})",
    "consequents": "frozenset({'Ice Cream'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Ice Cream'})",
    "consequents": "frozenset({'Cupcake'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Donut'})",
    "consequents": "frozenset({'Pancakes'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Pancakes'})",
    "consequents": "frozenset({'Donut'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Hummus & Pita'})",
    "consequents": "frozenset({'Falafel Wrap'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Falafel Wrap'})",
    "consequents": "frozenset({'Hummus & Pita'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Samosa'})",
    "consequents": "frozenset({'Falafel Wrap'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Falafel Wrap'})",
    "consequents": "frozenset({'Samosa'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Iced Herbal Tea'})",
    "consequents": "frozenset({'Fried Rice'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Fried Rice'})",
    "consequents": "frozenset({'Iced Herbal Tea'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Quesadilla'})",
    "consequents": "frozenset({'Fried Rice'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fried Rice'})",
    "consequents": "frozenset({'Quesadilla'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fries'})",
    "consequents": "frozenset({'Iced Herbal Tea'})",
    "antecedent support": 0.1,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 5,
    "representativity": 1,
    "leverage": 0.04,
    "conviction": 1.8,
    "zhangs_metric": 0.8888888888888888,
    "jaccard": 0.3333333333333333,
    "certainty": 0.4444444444444445,
    "kulczynski": 0.5
  },
  {
    "antecedents": "frozenset({'Iced Herbal Tea'})",
    "consequents": "frozenset({'Fries'})",
    "antecedent support": 0.1,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 5,
    "representativity": 1,
    "leverage": 0.04,
    "conviction": 1.8,
    "zhangs_metric": 0.8888888888888888,
    "jaccard": 0.3333333333333333,
    "certainty": 0.4444444444444445,
    "kulczynski": 0.5
  },
  {
    "antecedents": "frozenset({'Fries'})",
    "consequents": "frozenset({'Pizza'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Pizza'})",
    "consequents": "frozenset({'Fries'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Waffles'})",
    "consequents": "frozenset({'Fruit Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Fruit Bowl'})",
    "consequents": "frozenset({'Waffles'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Salad'})",
    "consequents": "frozenset({'Fruit Smoothie'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fruit Smoothie'})",
    "consequents": "frozenset({'Salad'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fruit Smoothie'})",
    "consequents": "frozenset({'Sandwich'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sandwich'})",
    "consequents": "frozenset({'Fruit Smoothie'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Mac & Cheese'})",
    "consequents": "frozenset({'Garlic Bread'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Garlic Bread'})",
    "consequents": "frozenset({'Mac & Cheese'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Pasta'})",
    "consequents": "frozenset({'Garlic Bread'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Garlic Bread'})",
    "consequents": "frozenset({'Pasta'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Soda'})",
    "consequents": "frozenset({'Garlic Bread'})",
    "antecedent support": 0.1,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 5,
    "representativity": 1,
    "leverage": 0.04,
    "conviction": 1.8,
    "zhangs_metric": 0.8888888888888888,
    "jaccard": 0.3333333333333333,
    "certainty": 0.4444444444444445,
    "kulczynski": 0.5
  },
  {
    "antecedents": "frozenset({'Garlic Bread'})",
    "consequents": "frozenset({'Soda'})",
    "antecedent support": 0.1,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 5,
    "representativity": 1,
    "leverage": 0.04,
    "conviction": 1.8,
    "zhangs_metric": 0.8888888888888888,
    "jaccard": 0.3333333333333333,
    "certainty": 0.4444444444444445,
    "kulczynski": 0.5
  },
  {
    "antecedents": "frozenset({'Muffin'})",
    "consequents": "frozenset({'Greek Yogurt'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Greek Yogurt'})",
    "consequents": "frozenset({'Muffin'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Trail Mix'})",
    "consequents": "frozenset({'Greek Yogurt'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Greek Yogurt'})",
    "consequents": "frozenset({'Trail Mix'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Green Tea'})",
    "consequents": "frozenset({'Ramen'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Ramen'})",
    "consequents": "frozenset({'Green Tea'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Green Tea'})",
    "consequents": "frozenset({'Sushi'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sushi'})",
    "consequents": "frozenset({'Green Tea'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Onion Rings'})",
    "consequents": "frozenset({'Hotdog'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Hotdog'})",
    "consequents": "frozenset({'Onion Rings'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Soda'})",
    "consequents": "frozenset({'Hotdog'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Hotdog'})",
    "consequents": "frozenset({'Soda'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Samosa'})",
    "consequents": "frozenset({'Hummus & Pita'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Hummus & Pita'})",
    "consequents": "frozenset({'Samosa'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Iced Herbal Tea'})",
    "consequents": "frozenset({'Quesadilla'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Quesadilla'})",
    "consequents": "frozenset({'Iced Herbal Tea'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Soda'})",
    "consequents": "frozenset({'Mac & Cheese'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Mac & Cheese'})",
    "consequents": "frozenset({'Soda'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Masala Dosa'})",
    "consequents": "frozenset({'Paneer Tikka'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Paneer Tikka'})",
    "consequents": "frozenset({'Masala Dosa'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Nachos'})",
    "consequents": "frozenset({'Protein Shake'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Protein Shake'})",
    "consequents": "frozenset({'Nachos'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Nachos'})",
    "consequents": "frozenset({'Tacos'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Tacos'})",
    "consequents": "frozenset({'Nachos'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Protein Shake'})",
    "consequents": "frozenset({'Omelette'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Omelette'})",
    "consequents": "frozenset({'Protein Shake'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Soda'})",
    "consequents": "frozenset({'Onion Rings'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Onion Rings'})",
    "consequents": "frozenset({'Soda'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Protein Shake'})",
    "consequents": "frozenset({'Tacos'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Tacos'})",
    "consequents": "frozenset({'Protein Shake'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Quinoa Bowl'})",
    "consequents": "frozenset({'Roasted Veggies'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Roasted Veggies'})",
    "consequents": "frozenset({'Quinoa Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sushi'})",
    "consequents": "frozenset({'Ramen'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Ramen'})",
    "consequents": "frozenset({'Sushi'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Salad'})",
    "consequents": "frozenset({'Sandwich'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sandwich'})",
    "consequents": "frozenset({'Salad'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sparkling Water'})",
    "consequents": "frozenset({'Sweet Potato Mash'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sweet Potato Mash'})",
    "consequents": "frozenset({'Sparkling Water'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sparkling Water'})",
    "consequents": "frozenset({'Tuna Salad'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Tuna Salad'})",
    "consequents": "frozenset({'Sparkling Water'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Tuna Salad'})",
    "consequents": "frozenset({'Sweet Potato Mash'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sweet Potato Mash'})",
    "consequents": "frozenset({'Tuna Salad'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Avocado Toast', 'Coffee'})",
    "consequents": "frozenset({'Fruit Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Avocado Toast', 'Fruit Bowl'})",
    "consequents": "frozenset({'Coffee'})",
    "antecedent support": 0.05,
    "consequent support": 0.15,
    "support": 0.05,
    "confidence": 1,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": "inf",
    "zhangs_metric": 0.8947368421052632,
    "jaccard": 0.3333333333333333,
    "certainty": 1,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Coffee', 'Fruit Bowl'})",
    "consequents": "frozenset({'Avocado Toast'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Avocado Toast'})",
    "consequents": "frozenset({'Coffee', 'Fruit Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Coffee'})",
    "consequents": "frozenset({'Avocado Toast', 'Fruit Bowl'})",
    "antecedent support": 0.15,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.33333333333333337,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": 1.425,
    "zhangs_metric": 1,
    "jaccard": 0.3333333333333333,
    "certainty": 0.29824561403508776,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Fruit Bowl'})",
    "consequents": "frozenset({'Avocado Toast', 'Coffee'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Masala Dosa', 'Biryani'})",
    "consequents": "frozenset({'Paneer Tikka'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Masala Dosa', 'Paneer Tikka'})",
    "consequents": "frozenset({'Biryani'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Biryani', 'Paneer Tikka'})",
    "consequents": "frozenset({'Masala Dosa'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Masala Dosa'})",
    "consequents": "frozenset({'Biryani', 'Paneer Tikka'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Biryani'})",
    "consequents": "frozenset({'Masala Dosa', 'Paneer Tikka'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Paneer Tikka'})",
    "consequents": "frozenset({'Masala Dosa', 'Biryani'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Protein Shake', 'Boiled Eggs'})",
    "consequents": "frozenset({'Omelette'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Protein Shake', 'Omelette'})",
    "consequents": "frozenset({'Boiled Eggs'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Boiled Eggs', 'Omelette'})",
    "consequents": "frozenset({'Protein Shake'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Protein Shake'})",
    "consequents": "frozenset({'Boiled Eggs', 'Omelette'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Boiled Eggs'})",
    "consequents": "frozenset({'Protein Shake', 'Omelette'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Omelette'})",
    "consequents": "frozenset({'Protein Shake', 'Boiled Eggs'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Cupcake', 'Ice Cream'})",
    "consequents": "frozenset({'Brownie'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Cupcake', 'Brownie'})",
    "consequents": "frozenset({'Ice Cream'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Ice Cream', 'Brownie'})",
    "consequents": "frozenset({'Cupcake'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Cupcake'})",
    "consequents": "frozenset({'Ice Cream', 'Brownie'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Ice Cream'})",
    "consequents": "frozenset({'Cupcake', 'Brownie'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Brownie'})",
    "consequents": "frozenset({'Cupcake', 'Ice Cream'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fries', 'Iced Herbal Tea'})",
    "consequents": "frozenset({'Burger'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fries', 'Burger'})",
    "consequents": "frozenset({'Iced Herbal Tea'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Iced Herbal Tea', 'Burger'})",
    "consequents": "frozenset({'Fries'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Fries'})",
    "consequents": "frozenset({'Iced Herbal Tea', 'Burger'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Iced Herbal Tea'})",
    "consequents": "frozenset({'Fries', 'Burger'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Burger'})",
    "consequents": "frozenset({'Fries', 'Iced Herbal Tea'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Trail Mix', 'Greek Yogurt'})",
    "consequents": "frozenset({'Cereal Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Trail Mix', 'Cereal Bowl'})",
    "consequents": "frozenset({'Greek Yogurt'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Greek Yogurt', 'Cereal Bowl'})",
    "consequents": "frozenset({'Trail Mix'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Trail Mix'})",
    "consequents": "frozenset({'Greek Yogurt', 'Cereal Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Greek Yogurt'})",
    "consequents": "frozenset({'Trail Mix', 'Cereal Bowl'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Cereal Bowl'})",
    "consequents": "frozenset({'Trail Mix', 'Greek Yogurt'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Cheesecake', 'Pasta'})",
    "consequents": "frozenset({'Garlic Bread'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Cheesecake', 'Garlic Bread'})",
    "consequents": "frozenset({'Pasta'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Pasta', 'Garlic Bread'})",
    "consequents": "frozenset({'Cheesecake'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Cheesecake'})",
    "consequents": "frozenset({'Pasta', 'Garlic Bread'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Pasta'})",
    "consequents": "frozenset({'Cheesecake', 'Garlic Bread'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Garlic Bread'})",
    "consequents": "frozenset({'Cheesecake', 'Pasta'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Chia Pudding', 'Quinoa Bowl'})",
    "consequents": "frozenset({'Roasted Veggies'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Chia Pudding', 'Roasted Veggies'})",
    "consequents": "frozenset({'Quinoa Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Quinoa Bowl', 'Roasted Veggies'})",
    "consequents": "frozenset({'Chia Pudding'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Chia Pudding'})",
    "consequents": "frozenset({'Quinoa Bowl', 'Roasted Veggies'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Quinoa Bowl'})",
    "consequents": "frozenset({'Chia Pudding', 'Roasted Veggies'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Roasted Veggies'})",
    "consequents": "frozenset({'Chia Pudding', 'Quinoa Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fries', 'Coconut Water'})",
    "consequents": "frozenset({'Pizza'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fries', 'Pizza'})",
    "consequents": "frozenset({'Coconut Water'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Coconut Water', 'Pizza'})",
    "consequents": "frozenset({'Fries'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Fries'})",
    "consequents": "frozenset({'Coconut Water', 'Pizza'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Coconut Water'})",
    "consequents": "frozenset({'Fries', 'Pizza'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Pizza'})",
    "consequents": "frozenset({'Fries', 'Coconut Water'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Donut', 'Coffee'})",
    "consequents": "frozenset({'Pancakes'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Donut', 'Pancakes'})",
    "consequents": "frozenset({'Coffee'})",
    "antecedent support": 0.05,
    "consequent support": 0.15,
    "support": 0.05,
    "confidence": 1,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": "inf",
    "zhangs_metric": 0.8947368421052632,
    "jaccard": 0.3333333333333333,
    "certainty": 1,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Coffee', 'Pancakes'})",
    "consequents": "frozenset({'Donut'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Donut'})",
    "consequents": "frozenset({'Coffee', 'Pancakes'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Coffee'})",
    "consequents": "frozenset({'Donut', 'Pancakes'})",
    "antecedent support": 0.15,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.33333333333333337,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": 1.425,
    "zhangs_metric": 1,
    "jaccard": 0.3333333333333333,
    "certainty": 0.29824561403508776,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Pancakes'})",
    "consequents": "frozenset({'Donut', 'Coffee'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Coffee', 'Waffles'})",
    "consequents": "frozenset({'Fruit Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Coffee', 'Fruit Bowl'})",
    "consequents": "frozenset({'Waffles'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Waffles', 'Fruit Bowl'})",
    "consequents": "frozenset({'Coffee'})",
    "antecedent support": 0.05,
    "consequent support": 0.15,
    "support": 0.05,
    "confidence": 1,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": "inf",
    "zhangs_metric": 0.8947368421052632,
    "jaccard": 0.3333333333333333,
    "certainty": 1,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Coffee'})",
    "consequents": "frozenset({'Waffles', 'Fruit Bowl'})",
    "antecedent support": 0.15,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.33333333333333337,
    "lift": 6.666666666666667,
    "representativity": 1,
    "leverage": 0.0425,
    "conviction": 1.425,
    "zhangs_metric": 1,
    "jaccard": 0.3333333333333333,
    "certainty": 0.29824561403508776,
    "kulczynski": 0.6666666666666667
  },
  {
    "antecedents": "frozenset({'Waffles'})",
    "consequents": "frozenset({'Coffee', 'Fruit Bowl'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Fruit Bowl'})",
    "consequents": "frozenset({'Coffee', 'Waffles'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Croissant', 'Muffin'})",
    "consequents": "frozenset({'Greek Yogurt'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Croissant', 'Greek Yogurt'})",
    "consequents": "frozenset({'Muffin'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Muffin', 'Greek Yogurt'})",
    "consequents": "frozenset({'Croissant'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Croissant'})",
    "consequents": "frozenset({'Muffin', 'Greek Yogurt'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Muffin'})",
    "consequents": "frozenset({'Croissant', 'Greek Yogurt'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Greek Yogurt'})",
    "consequents": "frozenset({'Croissant', 'Muffin'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Samosa', 'Hummus & Pita'})",
    "consequents": "frozenset({'Falafel Wrap'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Samosa', 'Falafel Wrap'})",
    "consequents": "frozenset({'Hummus & Pita'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Hummus & Pita', 'Falafel Wrap'})",
    "consequents": "frozenset({'Samosa'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Samosa'})",
    "consequents": "frozenset({'Hummus & Pita', 'Falafel Wrap'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Hummus & Pita'})",
    "consequents": "frozenset({'Samosa', 'Falafel Wrap'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Falafel Wrap'})",
    "consequents": "frozenset({'Samosa', 'Hummus & Pita'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Iced Herbal Tea', 'Quesadilla'})",
    "consequents": "frozenset({'Fried Rice'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Iced Herbal Tea', 'Fried Rice'})",
    "consequents": "frozenset({'Quesadilla'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Quesadilla', 'Fried Rice'})",
    "consequents": "frozenset({'Iced Herbal Tea'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Iced Herbal Tea'})",
    "consequents": "frozenset({'Quesadilla', 'Fried Rice'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Quesadilla'})",
    "consequents": "frozenset({'Iced Herbal Tea', 'Fried Rice'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fried Rice'})",
    "consequents": "frozenset({'Iced Herbal Tea', 'Quesadilla'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Salad', 'Fruit Smoothie'})",
    "consequents": "frozenset({'Sandwich'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Salad', 'Sandwich'})",
    "consequents": "frozenset({'Fruit Smoothie'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fruit Smoothie', 'Sandwich'})",
    "consequents": "frozenset({'Salad'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Salad'})",
    "consequents": "frozenset({'Fruit Smoothie', 'Sandwich'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Fruit Smoothie'})",
    "consequents": "frozenset({'Salad', 'Sandwich'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sandwich'})",
    "consequents": "frozenset({'Salad', 'Fruit Smoothie'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Soda', 'Mac & Cheese'})",
    "consequents": "frozenset({'Garlic Bread'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Soda', 'Garlic Bread'})",
    "consequents": "frozenset({'Mac & Cheese'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Mac & Cheese', 'Garlic Bread'})",
    "consequents": "frozenset({'Soda'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Soda'})",
    "consequents": "frozenset({'Mac & Cheese', 'Garlic Bread'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Mac & Cheese'})",
    "consequents": "frozenset({'Soda', 'Garlic Bread'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Garlic Bread'})",
    "consequents": "frozenset({'Soda', 'Mac & Cheese'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Green Tea', 'Sushi'})",
    "consequents": "frozenset({'Ramen'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Green Tea', 'Ramen'})",
    "consequents": "frozenset({'Sushi'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sushi', 'Ramen'})",
    "consequents": "frozenset({'Green Tea'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Green Tea'})",
    "consequents": "frozenset({'Sushi', 'Ramen'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sushi'})",
    "consequents": "frozenset({'Green Tea', 'Ramen'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Ramen'})",
    "consequents": "frozenset({'Green Tea', 'Sushi'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Soda', 'Onion Rings'})",
    "consequents": "frozenset({'Hotdog'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Soda', 'Hotdog'})",
    "consequents": "frozenset({'Onion Rings'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Onion Rings', 'Hotdog'})",
    "consequents": "frozenset({'Soda'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Soda'})",
    "consequents": "frozenset({'Onion Rings', 'Hotdog'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Onion Rings'})",
    "consequents": "frozenset({'Soda', 'Hotdog'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Hotdog'})",
    "consequents": "frozenset({'Soda', 'Onion Rings'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Nachos', 'Protein Shake'})",
    "consequents": "frozenset({'Tacos'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Nachos', 'Tacos'})",
    "consequents": "frozenset({'Protein Shake'})",
    "antecedent support": 0.05,
    "consequent support": 0.1,
    "support": 0.05,
    "confidence": 1,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": "inf",
    "zhangs_metric": 0.9473684210526315,
    "jaccard": 0.49999999999999994,
    "certainty": 1,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Protein Shake', 'Tacos'})",
    "consequents": "frozenset({'Nachos'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Nachos'})",
    "consequents": "frozenset({'Protein Shake', 'Tacos'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Protein Shake'})",
    "consequents": "frozenset({'Nachos', 'Tacos'})",
    "antecedent support": 0.1,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 0.5,
    "lift": 10,
    "representativity": 1,
    "leverage": 0.045,
    "conviction": 1.9,
    "zhangs_metric": 0.9999999999999999,
    "jaccard": 0.49999999999999994,
    "certainty": 0.4736842105263158,
    "kulczynski": 0.75
  },
  {
    "antecedents": "frozenset({'Tacos'})",
    "consequents": "frozenset({'Nachos', 'Protein Shake'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sparkling Water', 'Tuna Salad'})",
    "consequents": "frozenset({'Sweet Potato Mash'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sparkling Water', 'Sweet Potato Mash'})",
    "consequents": "frozenset({'Tuna Salad'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Tuna Salad', 'Sweet Potato Mash'})",
    "consequents": "frozenset({'Sparkling Water'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sparkling Water'})",
    "consequents": "frozenset({'Tuna Salad', 'Sweet Potato Mash'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Tuna Salad'})",
    "consequents": "frozenset({'Sparkling Water', 'Sweet Potato Mash'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  },
  {
    "antecedents": "frozenset({'Sweet Potato Mash'})",
    "consequents": "frozenset({'Sparkling Water', 'Tuna Salad'})",
    "antecedent support": 0.05,
    "consequent support": 0.05,
    "support": 0.05,
    "confidence": 1,
    "lift": 20,
    "representativity": 1,
    "leverage": 0.0475,
    "conviction": "inf",
    "zhangs_metric": 1,
    "jaccard": 1,
    "certainty": 1,
    "kulczynski": 1
  }
]

app = Flask(__name__)

# Load and preprocess rules
df = pd.DataFrame(data)

# Convert string frozensets to actual Python sets
df['antecedents'] = df['antecedents'].apply(lambda x: set(eval(x.replace("frozenset", ""))))
df['consequents'] = df['consequents'].apply(lambda x: set(eval(x.replace("frozenset", ""))))

@app.route('/', methods=['GET'])
def home():
    return '''Past purchases API'''

@app.route('/recommend/<string:txt>', methods=['GET'])
def recommend(txt):
    item = txt
    if not item:
        return jsonify({'error': 'Please provide an item'}), 400

    # Filter rules where the item is in the antecedents
    matching_rules = df[df['antecedents'].apply(lambda x: item in x)]

    if matching_rules.empty:
        return jsonify({'message': f'No recommendations found for {item}'}), 404

    # Sort rules by confidence (desc), then lift (desc)
    sorted_rules = matching_rules.sort_values(by=['confidence', 'lift'], ascending=False)

    # Extract top 2 unique recommended items
    seen_items = set()
    top_recommendations = []

    for _, row in sorted_rules.iterrows():
        for rec_item in row['consequents']:
            if rec_item not in seen_items:
                seen_items.add(rec_item)
                top_recommendations.append({
                    'recommended_items': [rec_item],
                    'confidence': row['confidence'],
                    'lift': row['lift']
                })
            if len(top_recommendations) >= 2:
                break
        if len(top_recommendations) >= 2:
            break

    return jsonify({
        'input_item': item,
        'recommendations': top_recommendations
    })

if __name__ == '__main__':
    app.run(debug=True)
